CXX = g++
CXXFLAGS = -g -O3 #-fopenmp
LFLAGS = -g -O3 #-fopenmp
LIBS = -lm 

## basic objects
BASIC_OBJS = NormalGrids2D.o NormalGrids3D.o GhostBC2D.o GhostFrame2D.o GhostFrame3D.o Center.o InnerSolvPatch.o MembranePatch.o InnerSolv.o Membrane.o util_funcs.o

## phase separation in inner solvent only, where chemical potential is calculated by double-well potential
SOLV_PS = solv_PS
SOLV_PS_OBJS = solv_PS.o 

## simple diffusion in inner solvent only, where chemical potential is equal to order parameter
SOLV_SD = solv_SD 
SOLV_SD_OBJS = solv_SD.o

## phase separation in membrane only, where chemical potential is calculated by double-well potential
MEMB_PS = memb_PS
MEMB_PS_OBJS = memb_PS.o 

## simple diffusion in membrane only, where chemical potential is equal to order parameter
MEMB_SD = memb_SD 
MEMB_SD_OBJS = memb_SD.o


all: solv_ps solv_sd memb_ps memb_sd

solv_ps: $(SOLV_PS) 
solv_sd: $(SOLV_SD)
memb_ps: $(MEMB_PS)
memb_sd: $(MEMB_SD)


$(SOLV_PS): $(BASIC_OBJS) $(SOLV_PS_OBJS) 
	$(CXX) $(LFLAGS) -o $@ $^ $(LIBS)
$(SOLV_PS_OBJS): 
	$(CXX) $(CXXFLAGS) -c $(SOLV_PS_OBJS:.o=.cpp)


$(SOLV_SD): $(BASIC_OBJS) $(SOLV_SD_OBJS) 
	$(CXX) $(LFLAGS) -o $@ $^ $(LIBS)
$(SOLV_SD_OBJS): 
	$(CXX) $(CXXFLAGS) -c $(SOLV_SD_OBJS:.o=.cpp)


$(MEMB_PS): $(BASIC_OBJS) $(MEMB_PS_OBJS) 
	$(CXX) $(LFLAGS) -o $@ $^ $(LIBS)
$(MEMB_PS_OBJS): 
	$(CXX) $(CXXFLAGS) -c $(MEMB_PS_OBJS:.o=.cpp)


$(MEMB_SD): $(BASIC_OBJS) $(MEMB_SD_OBJS) 
	$(CXX) $(LFLAGS) -o $@ $^ $(LIBS)
$(MEMB_SD_OBJS): 
	$(CXX) $(CXXFLAGS) -c $(MEMB_SD_OBJS:.o=.cpp)


$(BASIC_OBJS):
	$(CXX) $(CXXFLAGS) -c $(BASIC_OBJS:.o=.cpp)


clean:
	$(RM) *.o *~
	$(RM) .depend

cleanAll:
	$(RM) *.o *~
	$(RM) .depend
	$(RM) $(SOLV_PS) $(SOLV_SD) $(MEMB_PS) $(MEMB_SD)

depend:
	$(CXX) -MM $(CXXFLAGS) *.cpp > .depend

-include .depend
